server:
  port: 9000
  context-path: /serviceRegist
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false

    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9001${server.context-path}/eureka/
  server:
    enableSelfPreservation: false

