eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
