server:
  port: 8080
spring:
  jackson:
    serialization:
      indent_output: true
  application:
    name: admin
endpoints:
  health:
    sensitive: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:9000/serviceRegist/eureka/
